export const data = [
    {id:1,name:'gülər',link:"https://github.com/KenBroTech/django-search-project"},
    {id:2,name:'məhəmməd allahverdiyev',link:"https://github.com/Anonymous-0-0-7/Simple-Django-Project"},
    {id:3,name:'nəzrin',link:"https://github.com/benrobster/django-simple-db-storage"},
    {id:4,name:'hüseyn aşırov',link:"https://github.com/VojtechVavra/Django-simple-website"},
    {id:5,name:'niqar',link:"https://github.com/cooper09/djangoDemo"},
    {id:6,name:'ilkin bayramov',link:"https://github.com/Mahmud-007/SimpleDjangoDB"},
    {id:7,name:'samir',link:"https://github.com/KonstantinKonov/Django_simple"},
    {id:8,name:'fərid dəmirov',link:"https://github.com/diego0309/djangoMultiDb"},
    {id:9,name:'gokdeniz',link:"https://github.com/HRahman1777/end_game"},
    {id:10,name:'saməddin',link:"https://github.com/DiegoEvangelista15/Django---Invista-Project"},
    {id:11,name:'nicat',link:"https://github.com/pavantrinath/DjangoSearchApp"},
    {id:12,name:'vüsal',link:"https://github.com/vivaan19/Django-Personal-Projects"},
    {id:13,name:'aysu',link:"https://github.com/tybeck3/django-courses"},
    {id:14,name:'aysun',link:"https://github.com/MoinMN/django-project"},
    {id:15,name:'keklik ibrahim',link:"https://github.com/dodii/Databases-2020"},
    {id:16,name:'mehdiyev hüseyn',link:"https://github.com/milan-sony/django-CRUD"},
    {id:17,name:'kamran',link:"https://github.com/volchek00/Django_movie_app"},
    {id:18,name:'mirzəyev məhəmməd',link:"https://github.com/Aashishkumar123/bulk-file-uploader-django"},
    {id:19,name:'mirzəzadə hüseyn',link:"https://github.com/jod35/message_board"},
    {id:21,name:'ilkin məmmədov',link:"https://github.com/EricToCode/commerce"},
    {id:22,name:'nadirov fərid',link:"https://github.com/fadysherif8/Simple-Booking-Website"},
    {id:23,name:'mədət',link:"https://github.com/dinostroza/biblioteca"},
    {id:24,name:'ismayıl',link:"https://github.com/SagarDinkarNawale/Student-Info-System-"},
    {id:25,name:'furkan',link:"https://github.com/Zachary-Lei/BookingSystem"},
    {id:26,name:'hasan',link:"https://github.com/LonguiVic/First-Django-Project"},
    {id:27,name:'sahib',link:"https://github.com/ETCBishal/CRUD_Operation_in_django"}, 
]